require "mercadolibre/version"

# entities
require "mercadolibre/entity/answer"
require "mercadolibre/entity/auth"
require "mercadolibre/entity/category"
require "mercadolibre/entity/city"
require "mercadolibre/entity/country"
require "mercadolibre/entity/currency"
require "mercadolibre/entity/currency_conversion_ratio"
require "mercadolibre/entity/feedback"
require "mercadolibre/entity/item"
require "mercadolibre/entity/item_description"
require "mercadolibre/entity/item_picture"
require "mercadolibre/entity/listing_type"
require "mercadolibre/entity/order"
require "mercadolibre/entity/order_item"
require "mercadolibre/entity/payment"
require "mercadolibre/entity/payment_method"
require "mercadolibre/entity/phone"
require "mercadolibre/entity/question"
require "mercadolibre/entity/site"
require "mercadolibre/entity/site_domain"
require "mercadolibre/entity/state"
require "mercadolibre/entity/user"
require "mercadolibre/entity/zip_code"
# core
require "mercadolibre/core/auth"
require "mercadolibre/core/categories_and_listings"
require "mercadolibre/core/items_and_searches"
require "mercadolibre/core/locations_and_currencies"
require "mercadolibre/core/order_management"
require "mercadolibre/core/questions"
require "mercadolibre/core/users_and_apps"
require "mercadolibre/api"

# dependencies
require 'rest-client'
require 'singleton'
require 'time'
