require "mercadolibre/version"

# mercadolibre -> entities
require "mercadolibre/entity/address"
require "mercadolibre/entity/address_agency"
require "mercadolibre/entity/answer"
require "mercadolibre/entity/atm_transfer_reference"
require "mercadolibre/entity/auth"
require "mercadolibre/entity/billing_info"
require "mercadolibre/entity/card_configuration"
require "mercadolibre/entity/card_issuer"
require "mercadolibre/entity/category"
require "mercadolibre/entity/category_settings"
require "mercadolibre/entity/city"
require "mercadolibre/entity/collector"
require "mercadolibre/entity/cost_components"
require "mercadolibre/entity/country"
require "mercadolibre/entity/currency"
require "mercadolibre/entity/currency_conversion_ratio"
require "mercadolibre/entity/featured_item"
require "mercadolibre/entity/feedback"
require "mercadolibre/entity/feedback_reply"
require "mercadolibre/entity/geolocation"
require "mercadolibre/entity/gtin"
require "mercadolibre/entity/item"
require "mercadolibre/entity/item_attribute"
require "mercadolibre/entity/item_description"
require "mercadolibre/entity/item_payment_method"
require "mercadolibre/entity/item_picture"
require "mercadolibre/entity/item_shipping"
require "mercadolibre/entity/listing_exposure"
require "mercadolibre/entity/listing_price"
require "mercadolibre/entity/listing_type"
require "mercadolibre/entity/mediation"
require "mercadolibre/entity/mediation_interaction"
require "mercadolibre/entity/municipality"
require "mercadolibre/entity/neighborhood"
require "mercadolibre/entity/order"
require "mercadolibre/entity/order_coupon"
require "mercadolibre/entity/order_feedback"
require "mercadolibre/entity/order_item"
require "mercadolibre/entity/order_note"
require "mercadolibre/entity/order_shipping"
require "mercadolibre/entity/payment"
require "mercadolibre/entity/payment_method"
require "mercadolibre/entity/payment_plan"
require "mercadolibre/entity/payment_promotion"
require "mercadolibre/entity/phone"
require "mercadolibre/entity/product_identifier"
require "mercadolibre/entity/question"
require "mercadolibre/entity/search_location"
require "mercadolibre/entity/shipment"
require "mercadolibre/entity/shipment_status_history"
require "mercadolibre/entity/shipping_delivery"
require "mercadolibre/entity/shipping_item"
require "mercadolibre/entity/shipping_option"
require "mercadolibre/entity/shipping_speed"
require "mercadolibre/entity/site"
require "mercadolibre/entity/site_domain"
require "mercadolibre/entity/site_trend"
require "mercadolibre/entity/state"
require "mercadolibre/entity/user"
require "mercadolibre/entity/zip_code"

# mercadolibre -> core
require "mercadolibre/core/auth"
require "mercadolibre/core/categories_and_listings"
require "mercadolibre/core/items_and_searches"
require "mercadolibre/core/locations_and_currencies"
require "mercadolibre/core/order_management"
require "mercadolibre/core/shippings"
require "mercadolibre/core/questions"
require "mercadolibre/core/users"

# mercadolibre -> api
require "mercadolibre/api"

# mercadopago -> entities
require "mercadopago/entity/additional_info"
require "mercadopago/entity/address"
require "mercadopago/entity/auth"
require "mercadopago/entity/collector"
require "mercadopago/entity/fee_detail"
require "mercadopago/entity/identification"
require "mercadopago/entity/money_request"
require "mercadopago/entity/order"
require "mercadopago/entity/payer"
require "mercadopago/entity/payment"
require "mercadopago/entity/phone"
require "mercadopago/entity/refund"
require "mercadopago/entity/shipments"
require "mercadopago/entity/source"
require "mercadopago/entity/transaction_details"

# mercadopago -> core
require "mercadopago/core/auth"
require "mercadopago/core/payments"

# mercadopago -> api
require "mercadopago/api"

# dependencies
require 'rest-client'
require 'singleton'
require 'time'
